### PR TITLE
README.md: The name of the primary tbl is flights

### PR DESCRIPTION
**Pull request by sjackman**
The name of the of primary tbl was not mentioned. It's `flights`.

### CODE REVIEW

**Comment by ianmcook** [comment]
@sjackman the preceding sentence reads "it also includes a number of _other_ useful datasets" where "other" means not the `flights` dataset itself. That would need to be reworded.

**Comment by sjackman** [comment]
Done.

**Comment by hadley** [comment]
Thanks!

**Comment by sjackman** [comment]
Thanks for merging!

**Pull request merged**
